"""empty message

Revision ID: 100a6326d6eb
Revises: 64cf05f9523a
Create Date: 2023-03-28 21:22:01.782458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100a6326d6eb'
down_revision = '64cf05f9523a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
